### ISSUE TITLE
When training the MLP following error occurs. How do I solve it?

### ISSUE THREAD

**Issue by Ravindu-Yasas-Nagasinghe** [MCG-NJU/PDPP#3]
Traceback (most recent call last):
  File "train_mlp.py", line 480, in <module>
    main()
  File "train_mlp.py", line 170, in main
    mp.spawn(main_worker, nprocs=ngpus_per_node, args=(ngpus_per_node, args))
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 239, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 197, in start_processes
    while not context.join():
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 160, in join
    raise ProcessRaisedException(msg, error_index, failed_process.pid)
torch.multiprocessing.spawn.ProcessRaisedException: 

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/train_mlp.py", line 196, in main_worker
    train_dataset = PlanningDataset(
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 338, in __init__
    self.prepare_data()
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 383, in prepare_data
    vid_names.append(listdata['id'])
KeyError: 'id'

**Comment by pPetrichor** [comment]
Thanks for your question. By default, both 'args.json_path_val' and 'args.json_path_train' do not exist and will be generated by 'data_load_mlp.py'. During the generation process, we write every data with a key 'id'(Line 185, 257, 325). So maybe there exist some wrong 'args.json_path_val' and 'args.json_path_train' files that results in this error. You can try to delete these files and rerun the code.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Thank you very much for your response. However when I change line 383, 384 in to vid_names.append(listdata['vid']) and frame_cnts.append(listdata['length'])  in data_load_mlp.py file. Wrong keys have being assigned in the code. If you change into these the problem will be solved.

**Comment by pPetrichor** [comment]
May I know the value of your 'args.json_path_val' and 'args.json_path_train'?

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
parser.add_argument('--json_path_train',
                        type=str,
                        default='/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/train_list.json',
                        help='path of the generated json file for train')
    parser.add_argument('--json_path_val',
                        type=str,
                        default='/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/test_list.json',
                        help='path of the generated json file for val').

The locations are from my dataset location.

I tried out your suggestion by deleting these files and running but then it asks for these file locations.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Now I get the error,

-- Process 1 terminated with the following error:
Traceback (most recent call last):
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/multiprocessing/spawn.py", line 69, in _wrap
    fn(i, *args)
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/train_mlp.py", line 347, in main_worker
    losses = train(train_loader, args.n_train_steps, model, scheduler, args, optimizer, False).cuda()
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/train_mlp.py", line 413, in train
    batch = next(train_loader_)
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/train_mlp.py", line 27, in cycle
    for data in dl:
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/apps/local/anaconda3/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 450, in __getitem__
    frames, labels, task = self.sample_single(index)
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 416, in sample_single
    print(folder_id['task_id'])
TypeError: string indices must be integers

**Comment by pPetrichor** [comment]
Are the 'train_list.json' and 'test_list.json' provided by the repo in 'datasets'? And the content of them are like [{"vid": "GNJfDOoVORM", "task": "23521", "length": 5}, ...]. If so, you just use the split of dataset but not applied the sliding window operation to get action sequences for training. By default, both 'args.json_path_val' and 'args.json_path_train' do not exist, so you should give new path for them to generate these new files with 'dataload_mlp.py'.

**Comment by pPetrichor** [comment]
The 'train_list.json' and 'test_list.json' are the split of dataset. 'dataload_mlp.py' will read them and apply the sliding window operation and write the results to 'args.json_path_val' and 'args.json_path_train'. You can simply change, for example the 'args.json_path_val' like '/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/test_data.json', then this file will be generated as the results of actino sequences.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
yes they are the files provided by the repo in 'datasets' and content are like you mentioned. 
yes I changed them like below in args.py but it gives an error.
    parser.add_argument('--json_path_train',
                        type=str,
                        default = '',
                        help='path of the generated json file for train')
    parser.add_argument('--json_path_val',
                        type=str,
                        default='',
                        help='path of the generated json file for val')


Error is that:
  File "train_mlp.py", line 480, in <module>
    main()
  File "train_mlp.py", line 140, in main
    train_dataset = PlanningDataset(
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 191, in __init__
    with open(cross_task_data_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: ''

**Comment by pPetrichor** [comment]
'args.json_path_val' and 'args.json_path_train' should not be empty, they are the save paths of the sliding window results. You just need to give paths and generate them.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
When changed like mentioned by you,  

  parser.add_argument('--json_path_train',
                        type=str,
                        default='/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/crosstask_release/train_data_list.json',
                        help='path of the generated json file for train')
    parser.add_argument('--json_path_val',
                        type=str,
                        default='/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/crpsstask_release/test_data_list.json',
                        help='path of the generated json file for val')

Gives the error::

  File "train_mlp.py", line 480, in <module>
    main()
  File "train_mlp.py", line 147, in main
    test_dataset = PlanningDataset(
  File "/home/ravindu.nagasinghe/GithubCodes/PDPP/PDPP/dataloader/data_load_mlp.py", line 191, in __init__
    with open(cross_task_data_name, 'w') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/l/users/ravindu.nagasinghe/datasets/PDPP/CrossTask_assets/crpsstask_release/test_data_list.json'

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
Thank you very much for the support. 
I think the issue is fixed now.

**Comment by Ravindu-Yasas-Nagasinghe** [comment]
> Are the 'train_list.json' and 'test_list.json' provided by the repo in 'datasets'? And the content of them are like [{"vid": "GNJfDOoVORM", "task": "23521", "length": 5}, ...]. If so, you just use the split of dataset but not applied the sliding window operation to get action sequences for training. By default, both 'args.json_path_val' and 'args.json_path_train' do not exist, so you should give new path for them to generate these new files with 'dataload_mlp.py'.

solution
